name: CI

on:
  push:
    branches: [main]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [main]
    tags:
      - 'v*.*.*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
      
      - run: npm ci

      - run: npm run test

      - run: npm run coverage

      - run: npm run build

      - name: Save coverage badge data
        run: |
          mkdir -p .github/badges
          echo "{\"schemaVersion\":1,\"label\":\"coverage\",\"message\":\"${{ steps.coverage.outputs.coverage }}%\",\"color\":\"green\"}" > .github/badges/coverage.json

      - name: Upload badge artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .github/badges